### ISSUE TITLE
how to forward Messages?

### ISSUE THREAD

**Issue by ashenindeewara** [green-api/whatsapp-chatbot-python#16]
how to forward Messages?

**Comment by SomedayIsTheDay** [comment]
Hello, we are sorry, the method is currently unavailable, but we know about this problem, so you can expect it to be resolved soon.

**Comment by ashenindeewara** [comment]
> Hello, we are sorry, the method is currently unavailable, but we know about this problem, so you can expect it to be resolved soon.

ok thanks
