### ISSUE TITLE
is there a way to get the chat history /messages for a conversation ?

### ISSUE THREAD

**Issue by alexferra** [green-api/whatsapp-chatbot-python#23]
is there a way to get the chat history /messages for a conversation ?

**Comment by Jibek100** [comment]
Hello,
Please call the journals.getChatHistory method from the [whatsapp-api-client-python](https://github.com/green-api/whatsapp-api-client-python) library. In the chatbot you could access this API by notification.api.journals.getChatHistory(chatId=...).

See the full documentation of the method via the link https://green-api.com/en/docs/api/journals/GetChatHistory/
