### ISSUE TITLE
Any way to handle incoming WA calls via bot.router webhooks?

### ISSUE THREAD

**Issue by dimitrii9000** [green-api/whatsapp-chatbot-python#36]

**Comment by lent0s** [comment]
@dimitrii9000 
Good afternoon!
To process incoming call notifications, you must enable the `"incomingCallWebhook": "yes"` option in the **[instance settings](https://green-api.com/en/docs/api/account/SetSettings/)**
You can get acquainted with the type of webhook notifications about calls **[here](https://green-api.com/en/docs/api/recommendations/working-with-incomming-calls/)**

**Comment by lent0s** [comment]
@dimitrii9000 
At the moment, the bot does not have an incoming call handler. Clients can add it themselves. We will take your wishes into account and add this feature in future releases

**Comment by dimitrii9000** [comment]
Thanks!
For any other interested parties, it's quite easy to add custom handler to handle calls 
```python
from whatsapp_chatbot_python.manager.observer import Observer


class WhatsappMessageHandler:
    def __init__(self, bot: GreenAPIBot):
        self.bot = bot
        self.bot.router.incoming_call = Observer(self.bot.router)
        self.bot.router.observers["incomingCall"] = self.bot.router.incoming_call

        @self.bot.router.incoming_call()
        def message_handler(notification: Notification) -> None:
            logging.info(notification.event)
```
